"""add owner_id to locations

Revision ID: cd27d61c2cc2
Revises: f8a3c2b1d9e0
Create Date: 2026-05-07 14:46:24.309448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd27d61c2cc2'
down_revision: Union[str, Sequence[str], None] = 'f8a3c2b1d9e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'locations', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_column('locations', 'owner_id')
    # ### end Alembic commands ###
